Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  config.vm.define "stormBox" do |customBox|
    customBox.vm.box = "ubuntu/trusty64"
    customBox.vm.hostname = "storm.dev"
    customBox.vm.network :private_network, ip: "192.168.42.46"
    customBox.vm.provision :shell, path: "provisioner.sh"
  end
end
