Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.define "customBox" do |customBox|
    customBox.vm.box = "centos/7"
    customBox.vm.hostname = "customenv2.dev"
    customBox.vm.network :private_network, ip: "192.168.42.43"
  end
end
